name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - 'teste'

env:
  SERVICE: workspace-hub360
  SERVICE_BACKEND: workspace-hub360-api
  CLIENT_NAME: scs-demo
  REGION: us-central1
  KEYCLOAK_FILE: keycloak.demo.json

jobs:
  deploy_on_google_cloudrun:
    runs-on: ubuntu-latest
    name: Teste
    steps:
      - name: 'Checkout da versão'
        uses: actions/checkout@v2
      
      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Readme Button Action
        env:
          COLOR: "blue"
        run: |
          NEW_CONTENT="[![ REPLACED ](https://img.shields.io/badge/teste-blue)](https://google.com)"
          # Read the README.md content
          README_CONTENT=$(<README.md)

          # Replace the markers with the new content
          UPDATED_CONTENT="${README_CONTENT//REPLACE/$NEW_CONTENT}"

          # Write the updated content back to README.md
          echo -e "$UPDATED_CONTENT" > README.md

          echo "Content replaced successfully."
      - name: Commiting and Push
        run: |
          git add .
          git commit -m "docs(readme): Bump teste button"
          git branch github_actions_bot
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push -u origin github_actions_bot
